product:
    bar_code: ''
    brand_id: null
    category_id: 1210
    code: ''
    content_mobile: ''
    content_pc: o98pnaqC7ut4BZRC2bWylZ1z1GamHBlNZe8V3AF48u0YCIpHR0
    create_date: ''
    id: null
    is_del: 0
    is_discount: 1
    is_drugs: 0
    is_group: 0
    is_use: 0
    name: 258-PY实物商品88A1C99C
    pic: http://file.vetscloud.com/e4ac529178d1b5aeff9a2640a656d5c6,http://file.vetscloud.com/1390de573bb5e762988abb9ffdabcf02,http://file.vetscloud.com/1b7f2ab4d5b18644cac733887043629e,http://file.vetscloud.com/b14ed41b8f07ed04f113f57bc17cd6ba,http://file.vetscloud.com/7380845db1113453b2ceb7eb19a90527
    product_type: 1
    selling_point: 258-PY实物商品88A1C99C
    update_date: ''
    video: ''
    virtual_invalid_refund: 1
product_attr:
-   attr_id: 15
    attr_value_id: null
    id: null
    product_id: null
-   attr_id: 16
    attr_value_id: null
    id: null
    product_id: null
-   attr_id: 17
    attr_value_id: null
    id: null
    product_id: null
-   attr_id: 18
    attr_value_id: null
    id: null
    product_id: null
-   attr_id: 19
    attr_value_id: null
    id: null
    product_id: null
product_tags:
    age: 不限
    content_type: 不限
    is_sterilization: 不限
    product_type: 1
    sex: 不限
    special_stage: 不限
    species: 不限
    status: 不限
    varieties: 不限
sku_info:
-   bar_code: '1630224199'
    market_price: 182
    retail_price: 44
    sku_group: []
    sku_id: null
    sku_third:
    -   erp_id: 2
        erp_name: A8货号
        third_sku_id: '1341630223753'
    -   erp_id: 3
        erp_name: 管易货号
        third_sku_id: '9415525950'
    -   erp_id: 4
        erp_name: 子龙货号
        third_sku_id: '64316302242'
    skuv:
    -   id: null
        pic: http://file.vetscloud.com/8dd0266b7110206d7511a45b7ff4169a
        sku_id: null
        spec_id: 1
        spec_name: 种类
        spec_value_id: 1
        spec_value_value: 小型幼犬1.5KG
