config:
- headers:
    User-Agent: Mozilla/5.0 (Linux; Android 10; SPN-AL00 Build/HUAWEISPN-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/3121 MMWEBSDK/20210601 Mobile Safari/537.36 MMWEBID/751 MicroMessenger/8.0.11.1980(0x28000B3B) Process/appbrand0 WeChat/arm64 Weixin NetType/WIFI Language/zh_TW ABI/arm64 MiniProgramEnv/android
    content-type: application/json
    Accept-Encoding: gzip
    channel_id: 1
    user_agent: 3
- allures:
    feature: 小程序
    severity: normal
- request:
    method: get
    url:  [blockette,store_detail]
test_setup:
  view_store_details:
    allures:
      severity: critical
      story: 店铺
      title: 获取店铺基本信息
    request:
      params: {"channel_id": 1, finance_code: "${finance_code}"}
    validations:
      expected_code: 200
      expected_variables:
        $.code: ["eq",200]
        $.error: ["str_eq",""]
      expected_time: 10