ehrUserPosition: ''
isSuper: 0
nuanId: 0
roleType: 1
staffId: 10182
staffNameCn: 于艳青
structCompanyCode: RPX0001
structCompanyId: 2
structCompanyName: 瑞鹏公司
structId: 2
userEmail: ''
userGroupId: 0
userGroupName: null
userId: 9796
userMobile: '+8618174699611'
userName: yuyq
userNo: U_3B43GEA
userRealName: 于艳青
userStatus: 0
userStatusCn: 启用
userType: 1
userTypeCn: 员工
vetIdNumber: ''
